version: '3.8'

services:
  db:
    image: postgres:15
    container_name: sm_local_db
    volumes:
      - local_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./social_media_main/.postgres
  

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sm_local_web
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./social_media_main/.env
    depends_on:
      - db  


volumes:
  local_postgres_data:


