# Generated by Django 4.2 on 2024-03-27 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_useractivityconstraints_friendship_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivityconstraints',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
