# Generated by Django 4.2 on 2024-03-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_useractivityconstraints_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='rejected',
        ),
    ]
